<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Best Sellers</name>
   <tag></tag>
   <elementGuidId>77b5c826-0de1-4926-bb4e-d1e561d631b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.hmenu-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmenu-content']/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>723f289a-9bcd-4af5-a874-780dfd2a5e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gp/bestsellers/?ref_=nav_em_cs_bestsellers_0_1_1_2</value>
      <webElementGuid>c910115b-43e2-4eb1-b2bb-c1ae1d5cef63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmenu-item</value>
      <webElementGuid>b8671a92-b6cf-4b6e-83aa-5431e1c7145f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Best Sellers</value>
      <webElementGuid>94490bb2-8530-4e4d-be05-8e244cf338a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmenu-content&quot;)/ul[@class=&quot;hmenu hmenu-visible&quot;]/li[2]/a[@class=&quot;hmenu-item&quot;]</value>
      <webElementGuid>c9b24797-ddf9-4344-b101-3fe50efee416</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmenu-content']/ul/li[2]/a</value>
      <webElementGuid>964061a3-63ef-493f-807f-ff5c1e29b9a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Best Sellers')])[2]</value>
      <webElementGuid>2155542d-8b09-42e2-ad74-738727d22a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='trending'])[1]/following::a[1]</value>
      <webElementGuid>022646d2-0e5c-4cca-80a6-340a02c373d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello, sign in'])[2]/following::a[1]</value>
      <webElementGuid>5344200f-a57b-40f8-aade-9abde3c2c4ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Releases'])[2]/preceding::a[1]</value>
      <webElementGuid>36a04ca3-91e1-4d2b-ba58-195f8dbd406e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Movers and Shakers'])[1]/preceding::a[2]</value>
      <webElementGuid>64530027-863a-4429-b842-2dde578ddac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gp/bestsellers/?ref_=nav_em_cs_bestsellers_0_1_1_2')]</value>
      <webElementGuid>8fd34e28-e3e6-43ad-86d6-6904aa8bb534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[2]/a</value>
      <webElementGuid>e89bdb14-a03b-438a-8a27-f6794aa8efc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/gp/bestsellers/?ref_=nav_em_cs_bestsellers_0_1_1_2' and (text() = 'Best Sellers' or . = 'Best Sellers')]</value>
      <webElementGuid>9912590d-566e-46eb-bf53-ed488c5d0238</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
