<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bestsellers</name>
   <tag></tag>
   <elementGuidId>260fd19f-c6dc-4e46-bf69-f163616ddce3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._p13n-zg-nav-tab-all_style_zg-tabs-li-selected-div__3tHnP > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CardInstance68umyBcjTmrfuTsEelxuAQ']/div/ul/li/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dcc41f1d-ccca-403f-b8bc-bb71fb275a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gp/bestsellers/ref=zg_bs_tab_bs</value>
      <webElementGuid>dc3a36e6-39de-49d7-b947-43523be9c971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bestsellers</value>
      <webElementGuid>b63427a8-6abd-431f-89d8-6dcea230446f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardInstance68umyBcjTmrfuTsEelxuAQ&quot;)/div[@class=&quot;_p13n-zg-nav-tab-all_style_zg-tabs__EYPLq&quot;]/ul[1]/li[1]/div[@class=&quot;_p13n-zg-nav-tab-all_style_zg-tabs-li-selected-div__3tHnP&quot;]/a[1]</value>
      <webElementGuid>0f70e424-b91a-4d12-af86-979fd823dbb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CardInstance68umyBcjTmrfuTsEelxuAQ']/div/ul/li/div/a</value>
      <webElementGuid>8a21d63b-aebb-4a70-a674-6e26926044e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bestsellers')]</value>
      <webElementGuid>680d57b6-8fb9-45fb-8e6e-5739a84c7aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AmazonBasics'])[1]/following::a[3]</value>
      <webElementGuid>ce1c914e-fdcf-41f1-8093-6aa12b7aecfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe &amp; Save'])[2]/following::a[4]</value>
      <webElementGuid>f3d4fabe-ef28-4d12-8128-618cacd0f8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hot New Releases'])[1]/preceding::a[1]</value>
      <webElementGuid>03b7520a-9fcd-4622-beed-a4aa9a31d0e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Movers and Shakers'])[1]/preceding::a[2]</value>
      <webElementGuid>b3d870c5-6451-4a75-854b-7c9ebbc7483f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bestsellers']/parent::*</value>
      <webElementGuid>057063ec-b67d-41f3-b54f-e95a7e6ea46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gp/bestsellers/ref=zg_bs_tab_bs')]</value>
      <webElementGuid>5eaeef5f-b44d-4b88-b5fa-5147a0aa85b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/a</value>
      <webElementGuid>782f5f8d-271a-459d-b285-bf7d8ad97241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/gp/bestsellers/ref=zg_bs_tab_bs' and (text() = 'Bestsellers' or . = 'Bestsellers')]</value>
      <webElementGuid>ea4fd0c6-17df-4ec9-a4d0-7e1bb357cb2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
