<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>17c4506b-2aef-4965-9910-60aa8456de82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/header/div/div/div/div/a/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Saucelabs&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>568b053d-7160-402f-abde-3f39d301e955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Saucelabs</value>
      <webElementGuid>0041f145-8947-4e6d-a3ff-3fef1cd3780e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/logo.svg</value>
      <webElementGuid>bf9e4aa7-5892-4e4e-b793-7943c60502e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>1856a336-b6ba-433d-8e1f-97f7bd37e26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>intrinsic</value>
      <webElementGuid>ce2dc03d-f1dd-479c-85a9-0c20f7078670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/images/logo.svg 1x, /images/logo.svg 2x</value>
      <webElementGuid>7db316d8-10ff-41ab-9ea3-97a7c9ffefe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/header[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation4 MuiAppBar-root MuiAppBar-colorPrimary MuiAppBar-positionFixed mui-fixed css-fzuta4&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthXl MuiContainer-disableGutters css-1orecca&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-regular css-oxdlem&quot;]/div[@class=&quot;MuiStack-root css-19diydd&quot;]/div[@class=&quot;MuiBox-root css-11dv3qt&quot;]/a[1]/div[@class=&quot;MuiBox-root css-lwb5go&quot;]/span[1]/img[1]</value>
      <webElementGuid>9da0855c-f839-49ca-a130-764497c27221</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/header/div/div/div/div/a/div/span/img</value>
      <webElementGuid>ff167704-66a2-4a2f-951e-ffdff320c247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Saucelabs']</value>
      <webElementGuid>2953cda4-eec0-40c1-958e-44a67a145f38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>b9333c80-fb21-450e-91f6-d21f78b3cd84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Saucelabs' and @src = '/images/logo.svg']</value>
      <webElementGuid>a3cc1cb1-a5c8-49b3-9dd6-cdc8c95c95d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
