<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_All Deals_GridPresets-module__gridPrese_2ebf44</name>
   <tag></tag>
   <elementGuidId>670114f8-a405-4d52-a7a5-8a1dc045c15e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='anonCarousel1']/ol/li[2]/a/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>278f035d-bc5d-4de2-87c0-d1d859980208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/G/31/img20/Events/Jup21dealsgrid/blockbuster.jpg</value>
      <webElementGuid>944f703f-6af0-494d-9f35-6a881bd78493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GridPresets-module__gridPresetImage_1FnIo-Do5TDxU-XJMp1M77</value>
      <webElementGuid>37715d84-3b97-4116-bd86-d209c5642fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>85px</value>
      <webElementGuid>a2831f3e-9d71-463c-88e9-6107c8e84df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>85px</value>
      <webElementGuid>79fa24c0-a521-4e2a-8b8d-c286a846f571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anonCarousel1&quot;)/ol[@class=&quot;a-carousel&quot;]/li[@class=&quot;a-carousel-card GridPresets-module__gridPresetElement_LK6M4HpuBZHEa3NTWKSb9&quot;]/a[1]/span[@class=&quot;GridPresets-module__gridPresetImageSection_2p68sRHExZZwCJorBe2_N3&quot;]/img[@class=&quot;GridPresets-module__gridPresetImage_1FnIo-Do5TDxU-XJMp1M77&quot;]</value>
      <webElementGuid>ecf769f6-7753-463c-aa98-4bf3a77abb3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='anonCarousel1']/ol/li[2]/a/span/img</value>
      <webElementGuid>406dd52e-dad5-4cf1-be7f-dfe4a1027e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://m.media-amazon.com/images/G/31/img20/Events/Jup21dealsgrid/blockbuster.jpg')]</value>
      <webElementGuid>09d3a6f2-04c9-4848-a57a-ca21438dcf0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span/img</value>
      <webElementGuid>3b96a71a-89e4-4305-afc6-19d3f0353382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://m.media-amazon.com/images/G/31/img20/Events/Jup21dealsgrid/blockbuster.jpg']</value>
      <webElementGuid>ed0f5866-f8d3-4bb4-bcd2-609c05db415f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
